GroupBy,MergeOrJoin

In [ ]:
import pandas as pd

In [18]:
exp = pd.read_excel("subdata_pandas/expense.xlsx")
exp

         Date    Category       Sub-Category   Amount Payment Mode
0  2023-01-01     Grocery             Grocery      30         Cash
1  2023-01-02        Food          Restaurant     890          UPI
2  2023-01-04        Food              Zomato     257         Cash
3  2023-01-06  Essentials               Diary     120          UPI
4  2023-01-06  Essentials             Perfume    1500         Cash
5  2023-01-09     Grocery  Fruits and Veggies     456         Cash
6  2023-01-10       Bills          House Rent   16000         Card
7  2023-01-10     Grocery      Tomato KetchUp      70          UPI
8  2023-01-12        Food                Chai      15          UPI
9  2023-01-15  Essentials      Salt and Sugar      50         Cash
10 2023-01-17     Grocery           Chocolate     100          UPI
11 2023-01-17        Food          Restaurant     780         Card
12 2023-01-18  Essentials            Food Oil     120          UPI
13 2023-01-18        Food              Zomato     230          UPI
14 2023-01-19     Grocery                Milk      26          UPI
15 2023-01-20  Essentials             Shampoo     780          UPI
16 2023-01-20  Essentials           Lunch Box     890         Cash
17 2023-01-21     Clothes               Dress    1000         Card
18 2023-01-22     Clothes               Dress    1890          UPI
19 2023-01-23     Grocery      Bread and Milk      56         Cash
20 2023-01-24        Food  Fruits and Veggies     530         Cash
21 2023-01-26        Food                Chai      10          UPI
22 2023-01-26     Grocery               Maggi     140          UPI
23 2023-01-27        Food              Zomato     300          UPI
24 2023-01-27        Food                Chai      10          UPI
25 2023-01-28  Essentials           Bedsheets    1025         Cash
26 2023-01-29       Bills             Mobile     1650          UPI
27 2023-01-29     Grocery                Daal     150         Cash
28 2023-01-30       Bills            Cylinder    1074          UPI

In [37]:
exp.groupby("Category")['Amount'].sum()

Category
Bills         18724
Clothes        2890
Essentials     4485
Food           3022
Grocery        1028
Name: Amount, dtype: int64

In [20]:
exp.groupby('Payment Mode')["Amount"].agg(['sum'])

                sum
Payment Mode
Card          17780
Cash           4944
UPI            7425

In [38]:
exp.groupby("Category")['Amount'].agg(['sum'])

              sum
Category
Bills       18724
Clothes      2890
Essentials   4485
Food         3022
Grocery      1028

In [22]:
exp.groupby('Payment Mode')["Amount"].agg(['sum','count'])

                sum  count
Payment Mode
Card          17780      3
Cash           4944     10
UPI            7425     16

In [39]:
exp.groupby("Category")['Amount'].agg(['sum','mean','max','min'])

              sum         mean    max   min
Category
Bills       18724  6241.333333  16000  1074
Clothes      2890  1445.000000   1890  1000
Essentials   4485   640.714286   1500    50
Food         3022   335.777778    890    10
Grocery      1028   128.500000    456    26

In [25]:
exp.groupby(['Payment Mode','Category'])['Amount'].agg(['sum','count'])
exp.groupby(['Category','Payment Mode'])['Amount'].agg(['sum','count'])

                           sum  count
Category   Payment Mode
Bills      Card          16000      1
           UPI            2724      2
Clothes    Card           1000      1
           UPI            1890      1
Essentials Cash           3465      4
           UPI            1020      3
Food       Card            780      1
           Cash            787      2
           UPI            1455      6
Grocery    Cash            692      4
           UPI             336      4

In [26]:
exp.groupby("Category")['Amount'].sum().sort_values(ascending=False)

Category
Bills         18724
Essentials     4485
Food           3022
Clothes        2890
Grocery        1028
Name: Amount, dtype: int64

#---------------Task-----------------------
# Create a DataFrame containing the total expense of each category.
# What is the average transaction amount for each payment mode?
# Find the highest individual transaction in each category
# Show total, average, minimum and maximum transaction amount for each payment mode.

##MergeOrJoin

In [35]:
customer=pd.read_csv("subdata_pandas/customer1.csv")
customer
payment=pd.read_csv("subdata_pandas/payment.csv")
payment

   customerid  amount            mode paymentdate
0           1      60            Cash  2020-09-24
1          11      80            Cash  2021-03-01
2           2     500     Credit Card  2020-04-27
3           8     100            Cash  2021-01-26
4           7      20  Mobile Payment  2021-02-01
5          17     250     Credit Card  2021-04-01
6          10      70  Mobile Payment  2021-02-28

#Inner join

In [36]:
pd.merge(left=customer,right=payment,on='customerid',how='inner')

   customerid firstname lastname address  amount         mode paymentdate
0           1      Mary    Smith   Delhi      60         Cash  2020-09-24
1           2     Madan    Mohan  Mumbai     500  Credit Card  2020-04-27
2          17         R   Madhav     Goa     250  Credit Card  2021-04-01