Dealing with duplicate values,Missing Data

In [7]:
import pandas as pd
import numpy as np

Duplicate values

In [8]:
cdata=pd.read_csv("subdata_pandas/company.csv")
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [9]:
cdata.duplicated()
cdata[cdata.duplicated()]
cdata['EEID'].duplicated()
cdata[cdata['EEID'].duplicated()]
cdata.drop_duplicates()
cdata['EEID'].drop_duplicates()

0    EMP01
1    EMP02
2    EMP03
4    EMP05
5    EMP06
Name: EEID, dtype: str

In [12]:
cdata.isnull()
edata=pd.read_csv("subdata_pandas/employee.csv")
edata.isnull().sum()
cdata.isnull().sum()

EEID      0
Name      1
gender    1
salary    2
dtype: int64

In [13]:
cdata['salary'].isnull().sum()

np.int64(2)

In [13]:
#Replace NaN with any value
cdata.replace(np.nan,"Insufficient")
#Replace NaN with 30000 in salary
cdata['salary']=cdata['salary'].replace(np.nan, 30000)
#replaces NaN salary with average
mean=np.mean(cdata['salary'])
mean
#M1
#cdata['salary'].replace(np)
#cdata['salary']=cdata['salary'].replace(np.nan,mean)
#cdata
#M2
cdata['salary']=cdata['salary'].fillna(mean)
cdata
#forward fill(prev row)
cdata.ffill()
#backward fill(next row)
cdata.bfill()

    EEID      Name gender   salary
0  EMP01    ayushi      F  24400.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali      F  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05     rohit      M  25000.0
5  EMP06     rohit      M  24400.0
6  EMP02     rohit      M  25000.0