creation of data frames

In [2]:
import pandas as pd

In [3]:
student={
    'id':['CS080','CS117','CS116','CS105'],
    'name':['Mayur','Rohan','Rijesh','Pranav'],
    'age':[19,20,18,21]
}
#Creation of Dataframe
df=pd.DataFrame(student)
df

      id    name  age
0  CS080   Mayur   19
1  CS117   Rohan   20
2  CS116  Rijesh   18
3  CS105  Pranav   21

In [4]:
#Shape
df.shape
#size
df.size
#Columns
df.columns
#Rename
df.rename(columns={"id":"student_id"})

  student_id    name  age
0      CS080   Mayur   19
1      CS117   Rohan   20
2      CS116  Rijesh   18
3      CS105  Pranav   21

Export to csv file

In [6]:
df.to_csv("student_data.csv")
df.to_csv("student2_data.csv", index=False)

In [11]:
#same folder
df=pd.read_csv("companydemo.csv")
df
#diff folder
df1=pd.read_csv("D:/Placement training/pandas/subdata_pandas/student.csv")
df1

    id             name  age  marks   fees
0  101    Akshay Shetty   20     85  25000
1  102       Ananya Rao   21     92  30000
2  103   Rohit Bhandary   19     76  28000
3  104    Nisha D'Souza   20     88  25000
4  105  Karthik Poojary   22     69  32000
5  106    Shreya Shetty   19     95  30000
6  107       Rohan Naik   21     72  27000
7  108     Deepika Bhat   20     81  28000
8  109  Abhishek Kotian   22     64  26000
9  110        Pooja Rai   19     90  30000